apiVersion: apps/v1
kind: Deployment
metadata:
  name: stubhub-expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stubhub-expiration
  template:
    metadata:
      labels:
        app: stubhub-expiration
    spec:
      containers:
        - name: expiration
          image: maanasdevelopment/stubhub-expiration
          env:
            - name: REDIS_HOST
              value: "stubhub-expiration-redis-clusterip-srv"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://stubhub-nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: stubhub
